### ISSUE TITLE
TypeError: superclass mismatch for class Container

### ISSUE THREAD

**Issue by bemurphy** [icelab/dry-web-skeleton#51]
I'm trying out this skeleton to dip my toes in things, having been inspired by Tim's blog series.  I've played with the various components from scratch (dry-compontent, etc), but I'm having trouble with the skeleton.

When I try `bin/setup`, it errors when it hits the rake tasks for migration

```
TypeError: superclass mismatch for class Container
/private/tmp/dry/core/dry/container.rb:4:in `<module:Dry>'
/private/tmp/dry/core/dry/container.rb:3:in `<top (required)>'
/private/tmp/dry/Rakefile:13:in `require_relative'
/private/tmp/dry/Rakefile:13:in `<top (required)>'
/Users/bmurphy/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/Users/bmurphy/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/bmurphy/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/Users/bmurphy/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/Users/bmurphy/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/bmurphy/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/bmurphy/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/bmurphy/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/bmurphy/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/Users/bmurphy/.gem/ruby/2.3.1/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/Users/bmurphy/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/bmurphy/.gem/ruby/2.3.1/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/Users/bmurphy/.gem/ruby/2.3.1/bin/bundle:23:in `load'
/Users/bmurphy/.gem/ruby/2.3.1/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
rake aborted!
```

I'll dig in a little more to see if I can turn it up.  Any thoughts?

Thanks for your time.

**Comment by bemurphy** [comment]
Ahem, please forgive me, it's late/early here.  I just realized, when I setup I made my app name "dry" so I caused a massive namespace conflict.  Oops.
